#!/bin/sh
# 180904 stickyjwm-4.3 detect tray


valign=`grep -h 'autohide="off"' /root/.jwm/* -d skip|grep 'layer="above"'|grep -o "valign[^ ]*"|cut -d\" -f2`
height=`grep -h 'autohide="off"' /root/.jwm/* -d skip|grep 'layer="above"'|grep -o "height[^ ]*"|cut -d\" -f2`
if [[ $height == "" ]];then height=0;fi
#~ if [ $valign == "bottom" ];then
## info layar
	left=(`xrandr|grep " connected"|sed 's/primary //'|awk -F '[ x+]' '{print $1, $3, $4, $5, $6}'|sort -k4,4n -k5,5gr -k3,3gr|head -n 1`)
	right=(`xrandr|grep ' connected'|sed 's/primary //'|awk -F '[ x+]' '{print $1,$3,$4,$5,$6}'|sort -k4,4n -k5,5gr -k3,3gr|tail -n 1`)
#~ else
	#~ left=(`xrandr|grep " connected"|sed 's/primary //'|awk -F '[ x+]' '{print $1, $3, $4, $5, $6}'|sort -k4,4n -k5,5gr -k3,3gr|tail -n 1`)
	#~ right=(`xrandr|grep ' connected'|sed 's/primary //'|awk -F '[ x+]' '{print $1,$3,$4,$5,$6}'|sort -k4,4n -k5,5gr -k3,3gr|head -n 1`)
#~ fi

#sudah diubah belum susunan monitornya?
a=(`cat /tmp/stickyjwm/left`)
echo $a
echo ${left[@]}
if [ "${a[0]}" != "${left[0]}" ];then
	echo ndak sama
	rm /tmp/stickyjwm/*
else
	echo sama
fi
echo ${left[@]} > /tmp/stickyjwm/left

## 0   , 1, 2, 3, 4
## name, w, h, x, y

echo ${left[@]}

if [ $valign == "top" ];then
	left[4]=$(( ${left[4]} + $height ))
	left[2]=$(( ${left[2]} - $height ))
	#right[4]=$(( ${right[4]} + $height ))
	#right[2]=$(( ${right[2]} - $height ))
elif [ $valign == "bottom" ];then
	left[2]=$(( ${left[2]} - $height ))
	#right[2]=$(( ${right[2]} - $height ))
fi

echo $valign $height ${left[@]}


## Get window position
id_window=$(xprop -root|awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')
xwininfo -id $id_window>/tmp/$id_window
w_window=`awk '/Width/{print $2}' /tmp/$id_window`
h_window=`awk '/Height/{print $2}' /tmp/$id_window`
x_window=`awk '/Absolute\ upper\-left\ X/{print $4}' /tmp/$id_window`
y_window=`awk '/Absolute\ upper\-left\ Y/{print $4}' /tmp/$id_window`
border=`awk '/Relative\ upper\-left\ X/{print $4}' /tmp/$id_window`
title=`awk '/Relative\ upper\-left\ Y/{print $4}' /tmp/$id_window`

## Which screen is this window displayed in? If $x_window
## is greater than the offset of the rightmost screen,
## then the window is on the right hand one
if [ ! -f /tmp/stickyjwm/$id_window ];then
	mkdir -p /tmp/stickyjwm
	if [ "$x_window" -gt "${right[3]}" ]
	then
		current=(${right[@]})
		another=(${left[@]})
	else
		current=(${left[@]})
		another=(${right[@]})
	fi
	echo ${current[@]} > /tmp/stickyjwm/$id_window
	echo ${another[@]} >> /tmp/stickyjwm/$id_window
else
	current=(`cat /tmp/stickyjwm/$id_window|head -n 1`)
	another=(`cat /tmp/stickyjwm/$id_window|tail -n 1`)
fi
echo Window ini ada di layar ${current[0]}

echo $id_window, $w_window,$h_window,$x_window,$y_window,


# 1 | 2 | 3
#-----------
# 4 | 5 | 6
#-----------
# 7 | 8 | 9

# cek di posisi mana (1 - 9) window ini berada
# 1, 2, 3

# hasilnya

geser=100
ke_grid_terdekat=$(( $w_window%$geser ))
geser_sejauh=$(( $ke_grid_terdekat ))
echo $geser, $ke_grid_terdekat, $geser_sejauh

kiri_geser(){
	x=$(( $x_window - $geser_sejauh ))
	y=$y_window
	w=$(( ${current[1]} - $x_window + $geser_sejauh ))
	h=$h_window
}

kanan_geser(){
	x=0
	y=$y_window
	w=$(( $w_window - $geser_sejauh ))
	h=$h_window
}

# toleransi error
boleh=20

echo xwindow=$x_window,border=$border
echo ${current[1]}
selisih_x=$(($x_window-$border))
selisih_w=$(( ${current[1]} - $w_window - 2*$border))

echo selisih_x=$selisih_x
echo selisih_w=$selisih_w

# jika x_window menempel di sisi kiri
if [ $selisih_x -lt $boleh ];then
	echo x_window menempel sisi kiri
	#jika w_window = w_screen
	if [ $selisih_w -lt $boleh ];then
		kanan_geser
		echo kanangeser
	else
		kanan_geser
		echo kanan_geser
	fi
else
	kiri_geser
fi


echo selisihnya: ${selisih_w#-}, ${selisih_h#-}
w=$(( $w - 2*$border ))
#~ h=$(( $h - $title - $border ))
y=$(( $y - $title ))
echo $x,$y,$w,$h

# run twice to make terminal better place
wmctrl -r :ACTIVE: -e 0,$x,$y,$w,$h
wmctrl -r :ACTIVE: -e 1,$x,$y,$w,$h